jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials from N81092 account
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::905995217822:role/GitHubN81092
          aws-region: us-east-1
      - name: Display Identity
        run: aws sts get-caller-identity
on:
  workflow_dispatch:
