name: Deploy to S3

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      run: |
        echo "Setting up AWS credentials"
        echo "::set-env name=AWS_ROLE_ARN::arn:aws:iam::905995217822:role/OpenIDConnectGitHub"
        echo "::set-env name=AWS_WEB_IDENTITY_TOKEN_FILE::/tmp/github_token.txt"
    - name: Assume Role
      id: assume-role
      run: |
        echo "Assuming role with web identity"
        aws sts assume-role-with-web-identity --role-arn $AWS_ROLE_ARN --role-session-name "GitHubActionsSession" --web-identity-token file://$AWS_WEB_IDENTITY_TOKEN_FILE --duration-seconds 3600
   - name: Configure AWS credentials
       id: configure-aws-credentials
      uses: aws-actions/configure-aws-credentials@v1
        with:
      role-arn: arn:aws:iam::905995217822:role/OpenIDConnectGitHub
      provider: arn:aws:iam::905995217822:oidc-provider/token.actions.githubusercontent.com
    - name: Deploy to S3
      run: |
        echo "Deploying to S3"
        aws s3 cp . s3://ghdeploy/ --recursive
